---
title: "race"
author: "Jeremiah Kim"
date: "5/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
```




```{r}
data <- read_csv("data/FINAL_PUBLIC_DATA-4-23-20.csv", col_types = cols()) %>% 
        mutate(manipulated_race = ifelse(race != "White" & race != "Asian / Pacific Islander" & race != "Black or African American" & race != "Hispanic or Latino", "Other", race)) %>% 
        select(gender, race, first_meet, second_meet, third_meet, "fourth-meet", 
               id, first_id, second_id, third_id, fourth_id, know_street, know_by_name, know_annenberg, satisfied, manipulated_race)
```
      
      
      # Add this this to the shiny
      
```{r, Know Berg}

level_order <- c('0-20', '20-50', '50-100', '100-250', '250-500','500-1000')

      data %>% 
        group_by(manipulated_race) %>%
        count(know_annenberg) %>% 
        mutate(proportion = case_when(
          manipulated_race == "Asian / Pacific Islander" ~ n / 116,
          manipulated_race == "White" ~ n / 154, 
          manipulated_race == "Black or African American" ~ n / 32,
          manipulated_race == "Hispanic or Latino" ~ n / 29,
          manipulated_race == "Other" ~ n / 84)) %>% 
        ggplot(aes(x = factor(know_annenberg, level = level_order), y = proportion)) + 
        geom_col(fill = "purple") + 
        theme_economist() +
        facet_wrap(~manipulated_race) +
        theme(panel.spacing.x = unit(4, "mm"),
              panel.spacing.y =  unit(4, "mm"), 
              axis.text.x = element_text(angle=50, vjust = .5),
              axis.title.y = element_text(vjust = 2),
              strip.text.x = element_text(size = 10),
              plot.title = element_text(size = 14, vjust = 4),
              axis.title.x = element_blank()) +
        scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
        labs(title = "The Amount of classmates respondents would sit next to in Annenberg",
             y = "Proportion of respondents") 
```

```{r, satisfaction}
level_order <- c('Very Dissatisfied', 'Dissatisfied', 'Neutral', 'Satisfied', 'Very Satisfied')

data %>% 
        select(manipulated_race, satisfied) %>% 
        group_by(manipulated_race) %>% 
        count(satisfied) %>% 
        mutate(proportion = case_when(
          manipulated_race == "Asian / Pacific Islander" ~ n / 116,
          manipulated_race == "White" ~ n / 154, 
          manipulated_race == "Black or African American" ~ n / 32,
          manipulated_race == "Hispanic or Latino" ~ n / 29,
          manipulated_race == "Other" ~ n / 84)) %>% 
        ggplot(aes(x = factor(satisfied, level = level_order), y = proportion)) +
        geom_col(fill = "darkred") +
        theme_economist() +
        facet_wrap(~manipulated_race) +
        theme(panel.spacing.x = unit(4, "mm"),
              panel.spacing.y =  unit(4, "mm"), 
              axis.text.x = element_text(angle = 90, vjust = .5),
              axis.title.y = element_text(vjust = 2),
              strip.text.x = element_text(size = 10),
              plot.title = element_text(size = 14, vjust = 4),
              axis.title.x = element_blank()) +
        scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
        labs(title = "Social Satisfaction levels",
             y = "Proportion of respondents")
```




